### PR TITLE
Berdin

### PR DESCRIPTION
**Pull request by halal-money**
@sheggen I fulfilled everything, double checked the code and commented.

### CODE REVIEW

**Comment by sheggen** [comment]
You should not have created your code in hw03_stubs.py. That was a template file. If I accept your PR, it would ruin everyone else's ability to do the assignment, because you overwrote the sample file.

I'll help you fix this in class tomorrow. we'll need to move your code to a new file and revert this file.

**Comment by halal-money** [comment]
@sheggen I edited my code: https://github.com/Berea-College-CSC-226/hw03-main/tree/berdin

**Comment by halal-money** [comment]
@sheggen

**Comment by sheggen** [comment]
You still had changes getting pushed into hw03_stubs.py. However, they are just blank lines, so they should not harm anything, so I am going to accept the PR.

**Pull request merged**
